namespace SRPG
{
    using System;

    public enum BattleBonus
    {
        EffectRange,
        EffectScope,
        EffectHeight,
        HitRate,
        AvoidRate,
        CriticalRate,
        SlashAttack,
        PierceAttack,
        BlowAttack,
        ShotAttack,
        MagicAttack,
        ReactionAttack,
        JumpAttack,
        GainJewel,
        UsedJewelRate,
        ActionCount,
        GutsRate,
        AutoJewel,
        ChargeTimeRate,
        CastTimeRate,
        BuffTurn,
        DebuffTurn,
        CombinationRange,
        HpCostRate,
        SkillUseCount,
        PoisonDamage,
        PoisonTurn,
        Resist_Slash,
        Resist_Pierce,
        Resist_Blow,
        Resist_Shot,
        Resist_Magic,
        Resist_Reaction,
        Resist_Jump,
        Avoid_Slash,
        Avoid_Pierce,
        Avoid_Blow,
        Avoid_Shot,
        Avoid_Magic,
        Avoid_Reaction,
        Avoid_Jump,
        GainJewelRate,
        UsedJewel,
        UnitDefenseFire,
        UnitDefenseWater,
        UnitDefenseWind,
        UnitDefenseThunder,
        UnitDefenseShine,
        UnitDefenseDark
    }
}

