// Decompiled with JetBrains decompiler
// Type: SRPG.EMissionType
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 85BFDF7F-5712-4D45-9CD6-3465C703DFDF
// Assembly location: S:\Desktop\Assembly-CSharp.dll

namespace SRPG
{
  public enum EMissionType
  {
    [TowerQuestMissionType(QuestMissionProgressJudgeType.NotSupport), QuestMissionType(QuestMissionValueType.ValueIsNone)] KillAllEnemy,
    [QuestMissionType(QuestMissionValueType.ValueIsNone), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] NoDeath,
    [TowerQuestMissionType(QuestMissionProgressJudgeType.LessEqual), QuestMissionType(QuestMissionValueType.ValueIsInt)] LimitedTurn,
    [QuestMissionType(QuestMissionValueType.ValueIsInt)] ComboCount,
    [TowerQuestMissionType(QuestMissionProgressJudgeType.LessEqual), QuestMissionType(QuestMissionValueType.ValueIsInt)] MaxSkillCount,
    [QuestMissionType(QuestMissionValueType.ValueIsInt)] MaxItemCount,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] MaxPartySize,
    [QuestMissionType(QuestMissionValueType.ValueIsEnumName), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] LimitedUnitElement,
    [TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero), QuestMissionType(QuestMissionValueType.ValueIsString)] LimitedUnitID,
    [QuestMissionType(QuestMissionValueType.ValueIsNone)] NoMercenary,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.NotSupport)] Killstreak,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.LessEqual)] TotalHealHPMax,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.GreatorEqual)] TotalHealHPMin,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.LessEqual)] TotalDamagesTakenMax,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.GreatorEqual)] TotalDamagesTakenMin,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.LessEqual)] TotalDamagesMax,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.GreatorEqual)] TotalDamagesMin,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.NotSupport)] LimitedCT,
    [QuestMissionType(QuestMissionValueType.ValueIsInt)] LimitedContinue,
    [QuestMissionType(QuestMissionValueType.ValueIsNone)] NoNpcDeath,
    [QuestMissionType(QuestMissionValueType.ValueIsKeyAndIntValue), TowerQuestMissionType(QuestMissionProgressJudgeType.NotSupport)] TargetKillstreak,
    [QuestMissionType(QuestMissionValueType.ValueIsString)] NoTargetDeath,
    [TowerQuestMissionType(QuestMissionProgressJudgeType.LessEqual), QuestMissionType(QuestMissionValueType.ValueIsKeyAndIntValue)] BreakObjClashMax,
    [QuestMissionType(QuestMissionValueType.ValueIsKeyAndIntValue), TowerQuestMissionType(QuestMissionProgressJudgeType.GreatorEqual)] BreakObjClashMin,
    [QuestMissionType(QuestMissionValueType.ValueIsString)] WithdrawUnit,
    [QuestMissionType(QuestMissionValueType.ValueIsNone)] UseMercenary,
    [QuestMissionType(QuestMissionValueType.ValueIsString), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] LimitedUnitID_MainOnly,
    [QuestMissionType(QuestMissionValueType.ValueIsNone), TowerQuestMissionType(QuestMissionProgressJudgeType.NotSupport)] MissionAllCompleteAtOnce,
    [QuestMissionType(QuestMissionValueType.ValueIsStringArray), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] OnlyTargetArtifactType,
    [QuestMissionType(QuestMissionValueType.ValueIsStringArray), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] OnlyTargetArtifactType_MainOnly,
    [QuestMissionType(QuestMissionValueType.ValueIsStringArray), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] OnlyTargetJobs,
    [QuestMissionType(QuestMissionValueType.ValueIsStringArray), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] OnlyTargetJobs_MainOnly,
    [TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero), QuestMissionType(QuestMissionValueType.ValueIsString)] OnlyTargetUnitBirthplace,
    [QuestMissionType(QuestMissionValueType.ValueIsString), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] OnlyTargetUnitBirthplace_MainOnly,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] OnlyTargetSex,
    [TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero), QuestMissionType(QuestMissionValueType.ValueIsInt)] OnlyTargetSex_MainOnly,
    [QuestMissionType(QuestMissionValueType.ValueIsNone), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] OnlyHeroUnit,
    [TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero), QuestMissionType(QuestMissionValueType.ValueIsNone)] OnlyHeroUnit_MainOnly,
    [TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero), QuestMissionType(QuestMissionValueType.ValueIsString)] Finisher,
    [QuestMissionType(QuestMissionValueType.ValueIsInt)] TotalGetTreasureCount,
    [QuestMissionType(QuestMissionValueType.ValueIsString)] KillstreakByUsingTargetItem,
    [QuestMissionType(QuestMissionValueType.ValueIsString)] KillstreakByUsingTargetSkill,
    [TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero), QuestMissionType(QuestMissionValueType.ValueIsInt)] MaxPartySize_IgnoreFriend,
    [QuestMissionType(QuestMissionValueType.ValueIsNone), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] NoAutoMode,
    [QuestMissionType(QuestMissionValueType.ValueIsNone)] NoDeath_NoContinue,
    [QuestMissionType(QuestMissionValueType.ValueIsStringArray)] OnlyTargetUnits,
    [QuestMissionType(QuestMissionValueType.ValueIsStringArray)] OnlyTargetUnits_MainOnly,
    [TowerQuestMissionType(QuestMissionProgressJudgeType.LessEqual), QuestMissionType(QuestMissionValueType.ValueIsInt)] LimitedTurn_Leader,
    [QuestMissionType(QuestMissionValueType.ValueIsStringArray)] NoDeathTargetNpcUnits,
    [QuestMissionType(QuestMissionValueType.ValueIsInt)] UseTargetSkill,
    [QuestMissionType(QuestMissionValueType.ValueIsInt)] TotalKillstreakCount,
    [TowerQuestMissionType(QuestMissionProgressJudgeType.GreatorEqual), QuestMissionType(QuestMissionValueType.ValueIsInt)] TotalGetGemCount_Over,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.LessEqual)] TotalGetGemCount_Less,
    [QuestMissionType(QuestMissionValueType.ValueIsInt)] TeamPartySizeMax_IncMercenary,
    [QuestMissionType(QuestMissionValueType.ValueIsInt)] TeamPartySizeMax_NoMercenary,
    [TowerQuestMissionType(QuestMissionProgressJudgeType.LessEqual), QuestMissionType(QuestMissionValueType.ValueIsInt)] ChallengeCountMax,
    [TowerQuestMissionType(QuestMissionProgressJudgeType.LessEqual), QuestMissionType(QuestMissionValueType.ValueIsInt)] DeathCountMax,
  }
}
