// Decompiled with JetBrains decompiler
// Type: SRPG.TrophyConditionTypes
// Assembly: Assembly-CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 9BA76916-D0BD-4DB6-A90B-FE0BCC53E511
// Assembly location: C:\Users\André\Desktop\Assembly-CSharp.dll

namespace SRPG
{
  public enum TrophyConditionTypes
  {
    winquest,
    killenemy,
    getitem,
    playerlv,
    winelite,
    winevent,
    gacha,
    multiplay,
    ability,
    soubi,
    buygold,
    vip,
    stamina,
    card,
    arena,
    winarena,
    review,
    followtwitter,
    fggid,
    unitlevel,
    evolutionnum,
    joblevel,
    logincount,
    upunitlevel,
    makeunitlevel,
    unitequip,
    upjoblevel,
    makejoblevel,
    limitbreak,
    evoltiontimes,
    changejob,
    changeability,
    makeabilitylevel,
    winquestsoldier,
    winmulti,
    buyatshop,
    artifacttransmute,
    artifactstrength,
    artifactevolution,
    winmultimore,
    winmultiless,
    collectunits,
    totaljoblv11,
    totalunitlvs,
    childrencomp,
    wintower,
    losequest,
    loseelite,
    loseevent,
    losetower,
    losearena,
    dailyall,
    vs,
    vswin,
    vslose,
    fblogin,
  }
}
