// Decompiled with JetBrains decompiler
// Type: Battle_ChainSplash
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: FE644F5D-682F-4D6E-964D-A0DD77A288F7
// Assembly location: C:\Users\André\Desktop\Assembly-CSharp.dll

using UnityEngine;
using UnityEngine.UI;

[AddComponentMenu("UI/Drafts/Battle_ChainSplash")]
public class Battle_ChainSplash : UIDraft
{
  [UIDraft.AutoGenerated]
  public RawImage SplashImage;
}
