// Decompiled with JetBrains decompiler
// Type: MenuList_Item
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: FE644F5D-682F-4D6E-964D-A0DD77A288F7
// Assembly location: C:\Users\André\Desktop\Assembly-CSharp.dll

using UnityEngine;
using UnityEngine.UI;

[AddComponentMenu("UI/Drafts/MenuList_Item")]
public class MenuList_Item : UIDraft
{
  [UIDraft.AutoGenerated]
  public Text Text_Menu;
}
