// Decompiled with JetBrains decompiler
// Type: SelectArea
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: FE644F5D-682F-4D6E-964D-A0DD77A288F7
// Assembly location: C:\Users\André\Desktop\Assembly-CSharp.dll

using UnityEngine;
using UnityEngine.UI;

[AddComponentMenu("UI/Drafts/SelectArea")]
public class SelectArea : UIDraft
{
  [UIDraft.AutoGenerated]
  public Text Text_AreaName;
  [UIDraft.AutoGenerated]
  public Text Text_MenuTitle;
  [UIDraft.AutoGenerated]
  public Button Area_Item;
  [UIDraft.AutoGenerated]
  public Button Btn_Decide;
  [UIDraft.AutoGenerated]
  public Button Btn_BackWorld;
}
