// Decompiled with JetBrains decompiler
// Type: UIDraft
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: FE644F5D-682F-4D6E-964D-A0DD77A288F7
// Assembly location: C:\Users\André\Desktop\Assembly-CSharp.dll

using System;
using UnityEngine;

public abstract class UIDraft : MonoBehaviour
{
  protected UIDraft()
  {
    base.\u002Ector();
  }

  private void Start()
  {
    ((Behaviour) this).set_enabled(false);
  }

  public class AutoGenerated : Attribute
  {
  }

  public class ObsoleteHeader : PropertyAttribute
  {
    public readonly string header;

    public ObsoleteHeader(string header)
    {
      this.\u002Ector();
      this.header = header;
    }
  }
}
