// Decompiled with JetBrains decompiler
// Type: Win_Btn_DecideCancel_FL_Check_C
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: FE644F5D-682F-4D6E-964D-A0DD77A288F7
// Assembly location: C:\Users\André\Desktop\Assembly-CSharp.dll

using System;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.UI;

[AddComponentMenu("UI/Drafts/Win_Btn_DecideCancel_FL_Check_C")]
public class Win_Btn_DecideCancel_FL_Check_C : UIDraft
{
  [UIDraft.AutoGenerated]
  public Text Text_Message;
  [UIDraft.AutoGenerated]
  public Toggle Toggle;
  [UIDraft.AutoGenerated]
  public Button Btn_Cancel;
  [UIDraft.AutoGenerated]
  public Button Btn_Decide;
  public UIUtility.DialogResultEvent OnClickYes;
  public UIUtility.DialogResultEvent OnClickNo;
  [NonSerialized]
  public string ConfirmID;

  private void OnWindowClose(UIWindow window)
  {
    Object.DestroyImmediate((Object) ((Component) ((Component) this).GetComponentInParent<Canvas>()).get_gameObject());
  }

  private void BeginClose()
  {
    UIUtility.PopCanvas(true);
    UIWindow component = (UIWindow) ((Component) this).GetComponent<UIWindow>();
    component.OnWindowClose = new UIWindow.WindowEvent(this.OnWindowClose);
    component.Close();
  }

  private void OnClickButton(GameObject obj)
  {
    this.BeginClose();
    bool flag = Object.op_Equality((Object) obj, (Object) ((Component) this.Btn_Decide).get_gameObject());
    if (this.ConfirmID != null && this.ConfirmID.Length > 0)
    {
      int num1 = 0;
      if (PlayerPrefsUtility.HasKey(this.ConfirmID))
        num1 = PlayerPrefsUtility.GetInt(this.ConfirmID, 0);
      int num2 = !this.Toggle.get_isOn() ? 0 : 1;
      if (num1 != num2)
        PlayerPrefsUtility.SetInt(this.ConfirmID, num2, false);
    }
    if (flag)
    {
      if (this.OnClickYes == null)
        return;
      this.OnClickYes(((Component) this).get_gameObject());
    }
    else
    {
      if (this.OnClickNo == null)
        return;
      this.OnClickNo(((Component) this).get_gameObject());
    }
  }

  private void Awake()
  {
    UIUtility.AddEventListener(((Component) this.Btn_Decide).get_gameObject(), (UnityEvent) this.Btn_Decide.get_onClick(), new UIUtility.EventListener(this.OnClickButton));
    UIUtility.AddEventListener(((Component) this.Btn_Cancel).get_gameObject(), (UnityEvent) this.Btn_Cancel.get_onClick(), new UIUtility.EventListener(this.OnClickButton));
  }
}
