// Decompiled with JetBrains decompiler
// Type: QuestList_Item
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: FE644F5D-682F-4D6E-964D-A0DD77A288F7
// Assembly location: C:\Users\André\Desktop\Assembly-CSharp.dll

using UnityEngine;
using UnityEngine.UI;

[AddComponentMenu("UI/Drafts/QuestList_Item")]
public class QuestList_Item : UIDraft
{
  [UIDraft.AutoGenerated]
  public Image Clear;
  [UIDraft.AutoGenerated]
  public Text Text_QuestName;
  [UIDraft.AutoGenerated]
  public Text Text_PointNum;
  [UIDraft.AutoGenerated]
  public Text Text_Point;
}
