def GrowParam(json):
    this={}#GrowParamjson)
    #if(json==null)
    #returnfalse
    if 'type' in json:
        this['type'] = json['type']
    #if(json.curve!=null)
        #intlength=json.curve.Length
        #this.curve=newList<GrowSample>(length)
        #for(intindex=0index<length++index)
        #this.curve.Add(newGrowSample()
            #lv=(OInt)json.curve.lv,
            #scale=(OInt)json.curve.val,
            #status={
            #param={
            #hp=(OInt)json.curve.hp,
            #mp=(OShort)json.curve.mp,
            #atk=(OShort)json.curve.atk,
            #def=(OShort)json.curve.def,
            #mag=(OShort)json.curve.mag,
            #mnd=(OShort)json.curve.mnd,
            #dex=(OShort)json.curve.dex,
            #spd=(OShort)json.curve.spd,
            #cri=(OShort)json.curve.cri,
            #luk=(OShort)json.curve.luk
            #},
            #element_assist={
            #fire=(OShort)json.curve.afi,
            #water=(OShort)json.curve.awa,
            #wind=(OShort)json.curve.awi,
            #thunder=(OShort)json.curve.ath,
            #shine=(OShort)json.curve.ash,
            #dark=(OShort)json.curve.ada
            #},
            #element_resist={
            #fire=(OShort)json.curve.rfi,
            #water=(OShort)json.curve.rwa,
            #wind=(OShort)json.curve.rwi,
            #thunder=(OShort)json.curve.rth,
            #shine=(OShort)json.curve.rsh,
            #dark=(OShort)json.curve.rda
            #},
            #enchant_assist={
            #poison=(OShort)json.curve.apo,
            #paralyse=(OShort)json.curve.apa,
            #stun=(OShort)json.curve.ast,
            #sleep=(OShort)json.curve.asl,
            #charm=(OShort)json.curve.ach,
            #stone=(OShort)json.curve.asn,
            #blind=(OShort)json.curve.abl,
            #notskl=(OShort)json.curve.ans,
            #notmov=(OShort)json.curve.anm,
            #notatk=(OShort)json.curve.ana,
            #zombie=(OShort)json.curve.azo,
            #death=(OShort)json.curve.ade,
            #knockback=(OShort)json.curve.akn,
            #berserk=(OShort)json.curve.abe,
            #resist_buff=(OShort)json.curve.abf,
            #resist_debuff=(OShort)json.curve.adf,
            #stop=(OShort)json.curve.acs,
            #fast=(OShort)json.curve.acu,
            #slow=(OShort)json.curve.acd,
            #donsoku=(OShort)json.curve.ado,
            #rage=(OShort)json.curve.ara,
            #dec_ct=(OShort)json.curve.adc,
            #inc_ct=(OShort)json.curve.aic
            #},
            #enchant_resist={
            #poison=(OShort)json.curve.rpo,
            #paralyse=(OShort)json.curve.rpa,
            #stun=(OShort)json.curve.rst,
            #sleep=(OShort)json.curve.rsl,
            #charm=(OShort)json.curve.rch,
            #stone=(OShort)json.curve.rsn,
            #blind=(OShort)json.curve.rbl,
            #notskl=(OShort)json.curve.rns,
            #notmov=(OShort)json.curve.rnm,
            #notatk=(OShort)json.curve.rna,
            #zombie=(OShort)json.curve.rzo,
            #death=(OShort)json.curve.rde,
            #knockback=(OShort)json.curve.rkn,
            #berserk=(OShort)json.curve.rbe,
            #resist_buff=(OShort)json.curve.rbf,
            #resist_debuff=(OShort)json.curve.rdf,
            #stop=(OShort)json.curve.rcs,
            #fast=(OShort)json.curve.rcu,
            #slow=(OShort)json.curve.rcd,
            #donsoku=(OShort)json.curve.rdo,
            #rage=(OShort)json.curve.rra,
            #dec_ct=(OShort)json.curve.rdc,
            #inc_ct=(OShort)json.curve.ric
    #})
return this
