// Decompiled with JetBrains decompiler
// Type: QuestList_Item
// Assembly: Assembly-CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 9BA76916-D0BD-4DB6-A90B-FE0BCC53E511
// Assembly location: C:\Users\André\Desktop\Assembly-CSharp.dll

using UnityEngine;
using UnityEngine.UI;

[AddComponentMenu("UI/Drafts/QuestList_Item")]
public class QuestList_Item : UIDraft
{
  [UIDraft.AutoGenerated]
  public Image Clear;
  [UIDraft.AutoGenerated]
  public Text Text_QuestName;
  [UIDraft.AutoGenerated]
  public Text Text_PointNum;
  [UIDraft.AutoGenerated]
  public Text Text_Point;
}
