// Decompiled with JetBrains decompiler
// Type: SelectWorld
// Assembly: Assembly-CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 9BA76916-D0BD-4DB6-A90B-FE0BCC53E511
// Assembly location: C:\Users\André\Desktop\Assembly-CSharp.dll

using UnityEngine;
using UnityEngine.UI;

[AddComponentMenu("UI/Drafts/SelectWorld")]
public class SelectWorld : UIDraft
{
  [UIDraft.AutoGenerated]
  public Button World_Item;
  [UIDraft.AutoGenerated]
  public Text Text_WorldName;
  [UIDraft.AutoGenerated]
  public Text Text_MenuTitle;
  [UIDraft.AutoGenerated]
  public Button Btn_Decide;
}
