// Decompiled with JetBrains decompiler
// Type: SelectArea
// Assembly: Assembly-CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 9BA76916-D0BD-4DB6-A90B-FE0BCC53E511
// Assembly location: C:\Users\André\Desktop\Assembly-CSharp.dll

using UnityEngine;
using UnityEngine.UI;

[AddComponentMenu("UI/Drafts/SelectArea")]
public class SelectArea : UIDraft
{
  [UIDraft.AutoGenerated]
  public Text Text_AreaName;
  [UIDraft.AutoGenerated]
  public Text Text_MenuTitle;
  [UIDraft.AutoGenerated]
  public Button Area_Item;
  [UIDraft.AutoGenerated]
  public Button Btn_Decide;
  [UIDraft.AutoGenerated]
  public Button Btn_BackWorld;
}
