// Decompiled with JetBrains decompiler
// Type: Title
// Assembly: Assembly-CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 9BA76916-D0BD-4DB6-A90B-FE0BCC53E511
// Assembly location: C:\Users\André\Desktop\Assembly-CSharp.dll

using UnityEngine;
using UnityEngine.UI;

[AddComponentMenu("UI/Drafts/Title")]
public class Title : UIDraft
{
  [UIDraft.AutoGenerated]
  public Button Button_TapStart;
  [UIDraft.AutoGenerated]
  public Button Button_NewGame;
}
