// Decompiled with JetBrains decompiler
// Type: UIDraft
// Assembly: Assembly-CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 9BA76916-D0BD-4DB6-A90B-FE0BCC53E511
// Assembly location: C:\Users\André\Desktop\Assembly-CSharp.dll

using System;
using UnityEngine;

public abstract class UIDraft : MonoBehaviour
{
  protected UIDraft()
  {
    base.\u002Ector();
  }

  private void Start()
  {
    ((Behaviour) this).set_enabled(false);
  }

  public class AutoGenerated : Attribute
  {
  }

  public class ObsoleteHeader : PropertyAttribute
  {
    public readonly string header;

    public ObsoleteHeader(string header)
    {
      this.\u002Ector();
      this.header = header;
    }
  }
}
